const types = {
  NOTIFICATION_GET_REQUEST: "NOTIFICATION_GET_REQUEST",
  NOTIFICATION_GET_SUCCESS: "NOTIFICATION_GET_SUCCESS",
  NOTIFICATION_GET_FAILED: "NOTIFICATION_GET_FAILED",

  NOTIFICATION_READ_REQUEST: "NOTIFICATION_READ_REQUEST",
  NOTIFICATION_READ_SUCCESS: "NOTIFICATION_READ_SUCCESS",
  NOTIFICATION_READ_FAILED: "NOTIFICATION_READ_FAILED",
}

export default types
