export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILED = 'PRODUCT_LIST_FAILED';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAILED = 'PRODUCT_DETAIL_FAILED';

export const BUY_PRODUCTS_SUCCESS = 'BUY_PRODUCTS_SUCCESS';
export const BUY_PRODUCTS_REQUEST = 'BUY_PRODUCTS_REQUEST';
export const BUY_PRODUCTS_FAILED = 'BUY_PRODUCTS_FAILED';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const CHECK_PROMO_REQUEST = 'CHECK_PROMO_REQUEST';
export const CHECK_PROMO_SUCCESS = 'CHECK_PROMO_SUCCESS';
export const CHECK_PROMO_ERROR = 'CHECK_PROMO_ERROR';

export const CLEAR_PROMO = 'CLEAR_PROMO';

export const SET_SCROLL_AND_OFFSET = 'SET_SCROLL_AND_OFFSET';
export const INFINITE_SCROLL_AND_OFFSET = 'INFINITE_SCROLL_AND_OFFSET';
